### ISSUE TITLE
Allow creating deduplicated FIFO queues

### ISSUE THREAD

**Issue by musketyr** [agorapulse/micronaut-aws-sdk#120]

**Comment by henryju** [comment]
Would be great to support passing the `ContentBasedDeduplication` attribute when creating a queue.

**Comment by musketyr** [comment]
Hi, I will try to take look once I got a bit of time. If you have a bit of time yourself - the place you want to look is

https://github.com/agorapulse/micronaut-aws-sdk/blob/master/subprojects/micronaut-amazon-awssdk-sqs/src/main/java/com/agorapulse/micronaut/amazon/awssdk/sqs/QueueConfiguration.java

and

https://github.com/agorapulse/micronaut-aws-sdk/blob/master/subprojects/micronaut-amazon-awssdk-sqs/src/main/java/com/agorapulse/micronaut/amazon/awssdk/sqs/DefaultSimpleQueueService.java#L85

**Comment by henryju** [comment]
Thanks for considering this. I found a workaround by creating the queue manually in the tests:

```
@Singleton
public class SqsClientCreatedEventListener implements BeanCreatedEventListener<SqsClient> {
  public static final String QUEUE_NAME = "MyQueue";

  @Override
  public SqsClient onCreated(BeanCreatedEvent<SqsClient> event) {
    SqsClient client = event.getBean();
    if (client.listQueues().queueUrls().stream().noneMatch(it -> it.contains(QUEUE_NAME))) {
      client.createQueue(
        CreateQueueRequest.builder()
          .queueName(QUEUE_NAME)
          .attributes(Map.of(
            QueueAttributeName.FIFO_QUEUE, Boolean.TRUE.toString(),
            QueueAttributeName.CONTENT_BASED_DEDUPLICATION, Boolean.TRUE.toString()
          ))
          .build()
      );
    }
    return client;
  }
}
```
