### ISSUE TITLE
Add support for aws sdk2 specially kinesis

### ISSUE THREAD

**Issue by rverma-nikiai** [agorapulse/micronaut-aws-sdk#34]
Aws sdkv2 using kcl2 supports http2 which is a great advantage. Please consider upgrading the aws sdk.

**Comment by musketyr** [comment]
this is definitely in the pipeline. the full upgrade is currently blocked by https://github.com/aws/aws-sdk-java-v2/issues/35 but we'll try to find out a solution to provide v2 services as well.

**Comment by SchulteMarkus** [comment]
Maybe change the title here to s.th. like "move to aws-sdk-java-v2"?

**Comment by musketyr** [comment]
hi, I the work has started. version `1.3.4` has solved the major obstacle - DynamoDB v2, the other clients should follow soon

**Comment by gregorydickson** [comment]
+1 and thanks for the great library

**Comment by musketyr** [comment]
the v2 support is officially out starting with `1.4.0`
