### ISSUE TITLE
Do not inherit Groovy to projects using micronaut-libraries

### ISSUE THREAD

**Issue by SchulteMarkus** [agorapulse/micronaut-aws-sdk#39]
Hi there,

we are using your lovely micronaut-libraries within our project. Long story short: A Micronaut function running in AWS Lambda. 

**Current state**

```
$ ./gradlew dependencies
...
+--- com.agorapulse:micronaut-aws-sdk:1.2.5
|    +--- org.codehaus.groovy:groovy:2.5.8 -> 2.5.6
|    +--- io.micronaut:micronaut-runtime-groovy:1.1.1
|    |    +--- org.codehaus.groovy:groovy:2.5.6
...
```

com.agorapulse:micronaut-aws-sdk is build on top of org.codehaus.groovy:groovy. While I normally would not care, in our use case this is a disadvantage. The required groovy-2.5.6.jar has (uncompressed) 5.5MB in size, which makes 20% of the fat jar we are deploying to AWS Lambda.

**Wish**: Do not inherit Groovy to projects using com.agorapulse:micronaut-aws-sdk

**Comment by musketyr** [comment]
this is for historical reasons as the libraries are a successor of https://github.com/agorapulse/grails-aws-sdk

will be probably removed as a part of the afford to be compatible with GraalVM native image

**Comment by musketyr** [comment]
just to let you know, the libraries compatible with AWS SDK v2 will not require Groovy

**Comment by musketyr** [comment]
v2 implementations are now officially release. use these if you don't want the Groovy dependency
