### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by fmonorchio** [agorapulse/micronaut-aws-sdk#56]
Hi all,

I want to use the Micronaut AWS SDK for SES but, when adding the dependency for version 1.3.2, gradle complains that the parent pom "com.agorapulse:micronaut-aws-sdk-dependencies" not exists.

Thanks

**Comment by musketyr** [comment]
Hi, sorry for late reply. I'm waiting for a reply from a BinTray team.

You can fix this issue by pointing to our BinTray repo directly:

https://bintray.com/agorapulse/libs

**Comment by fmonorchio** [comment]
I have added the repository but now there is another error:

Could not parse POM: The markup in the document preceding the root element must be well-formed.

I'm using Gradle 6.2.2

**Comment by musketyr** [comment]
is there any chance you have entered HTTP URL `http://bintray.com/agorapulse/libs` instead of HTTPS URL `https://bintray.com/agorapulse/libs`?

I've tried the following:

1) installed the latest micronaut
```
sdk install micronaut 1.3.4
```
2) replaced version in `gradle/gradle-wrapper.properties` to `6.2.2`

3) added agorapulse libraries repo

```
repositories {
    mavenCentral()
    maven { url "https://jcenter.bintray.com" }
    maven {
        url  "http://dl.bintray.com/agorapulse/libs"
    }
}
```

4) added dynamodb dependency

```

dependencies {
    implementation 'com.agorapulse:micronaut-aws-sdk-dynamodb:1.3.2'
    // ...
}
```

and it works for me. is there any step you made differently?

**Comment by fmonorchio** [comment]
I copied this "https://bintray.com/agorapulse/libs" from your first post but, the correct url is this "https://dl.bintray.com/agorapulse/libs".

Now it works! Thanks @musketyr

**Comment by musketyr** [comment]
oh, sorry about that! I'm glad it works for you now. I hope I will figure out how to solve the issue with JCenter inclusion

**Comment by musketyr** [comment]
FYI the request for inclusion was finally successfully sent so from version `1.3.4` onward there should be no need to include the URL
