### ISSUE TITLE
Implementation of get(Object hashKey) in public interface DynamoDBService<T> {

### ISSUE THREAD

**Issue by gregorydickson** [agorapulse/micronaut-aws-sdk#62]
In public interface DynamoDBService<T> 

There is a method defined (on the interface):
```
/**
     * Load an item
     *
     * @param hashKey
     * @return
     */
    default T get(Object hashKey) {
        return get(hashKey, null);
    }
```

Update: the default implementation of get(Object hashKey) seems to fail with an exception:
of no RANGE key value present.

**Comment by musketyr** [comment]
There's no need to implement a default method in an implementing classes.

**Comment by gregorydickson** [comment]
Right, I didn't read the code correctly when I first was digging into the issue. I am calling get(Object hashKey) and receiving an exception of no Range key value present. I will attempt to duplicate with a sample project.

**Comment by musketyr** [comment]
Ok. If your table has both - hash and range key, then you need to use the method with the range key

**Comment by gregorydickson** [comment]
Ok, I now understand my error. thanks!
