### ISSUE TITLE
[Question] Have dynamic table names in awssdkv2

### ISSUE THREAD

**Issue by joseybv** [agorapulse/micronaut-aws-sdk#82]
As outlined on issue #55 it is necessary to be able to have dynamic table names. it would be awesome to simply be able to read from application.yml

the code shared on the issue above does work. but none of the classes used are available on awssdkv2

`com.agorapulse:micronaut-amazon-awssdk-dynamodb:1.4.0`

`@Service(value = Object.class, tableName = "${aws.table.objects}")`

**Comment by musketyr** [comment]
You are right. Let's see what can be improved related to this topic for AWS SDK V2 implementation.

**Comment by musketyr** [comment]
hi. sorry for a late reply. the property resolution you have mentioned already works. see https://github.com/agorapulse/micronaut-aws-sdk/commit/19ae9269a9f90376048205a9f0354c9623b14b20 for the reference

**Comment by joseybv** [comment]
Thats exactly how it should work. Thanks a lot!
