### ISSUE TITLE
Generate presignedUrl for PUT request?

### ISSUE THREAD

**Issue by vitality82** [agorapulse/micronaut-aws-sdk#84]
The current method for S3 "generatePresignedUrl" seems to generate a "PresignedGetObjectRequest" under the hood.
Is there a way to generate a presignedURL for a "PUT" request so that the URL can be used for direct uploads?

**Comment by musketyr** [comment]
Hi, sorry for late response, we're internally using [SecurityTokenService](https://github.com/agorapulse/micronaut-aws-sdk/blob/master/subprojects/micronaut-aws-sdk-sts/src/main/groovy/com/agorapulse/micronaut/aws/sts/SecurityTokenService.java) but I can see there is another way how to do it as you described. I will take a look next week as there are other improvements to make in this library as well.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html
